export const baseDataset = [
    {
        name: 'Animales',
        words: [
            { word: 'perro' },
            { word: 'gato' },
            { word: 'loro' },
            { word: 'canguro' },
            { word: 'ballena' },
            { word: 'tiburon' },
            { word: 'rinoceronte' },
            { word: 'pinguino' },
            { word: 'alpaca' },
            { word: 'iguana' },
            { word: 'mapache' },
            { word: 'zorro' },
            { word: 'leon' },
            { word: 'tigre' },
            { word: 'oso' },
            { word: 'panda' },
            { word: 'koala' },
            { word: 'delfin' },
            { word: 'tortuga' },
            { word: 'caballo' },
            { word: 'burro' },
            { word: 'cordero' },
            { word: 'cabra' },
            { word: 'pato' },
            { word: 'gallina' },
            { word: 'hipopotamo' },
            { word: 'jirafa' },
            { word: 'elefante' },
            { word: 'hiena' },
            { word: 'pantera' },
            { word: 'lince' },
            { word: 'camello' },
        ]
    },
    {
        name: 'Comida',
        words: [
            { word: 'ceviche' },
            { word: 'cuy' },
            { word: 'encebollado' },
            { word: 'bolon' },
            { word: 'hamburguesa' },
            { word: 'pizza' },
            { word: 'sushi' },
            { word: 'taco' },
            { word: 'arepa' },
            { word: 'lasagna' },
            { word: 'helado' },
            { word: 'ramen' },
            { word: 'tostada' },
            { word: 'brownie' },
            { word: 'chocolate' },
            { word: 'galleta' },
            { word: 'panqueque' },
            { word: 'waffle' },
            { word: 'burrito' },
            { word: 'quesadilla' },
            { word: 'empanada' },
            { word: 'tamal' },
            { word: 'paella' },
            { word: 'risotto' },
            { word: 'flan' },
            { word: 'tiramisu' },
            { word: 'churro' },
            { word: 'alfajor' },
            { word: 'pastel' },
            { word: 'fajitas' },
            { word: 'ceviche' },
            { word: 'arequipe' },
        ]
    },
    {
        name: 'Peliculas',
        words: [
            { word: 'avatar' },
            { word: 'matrix' },
            { word: 'inception' },
            { word: 'coco' },
            { word: 'gladiador' },
            { word: 'top gun' },
            { word: 'frozen' },
            { word: 'titanic' },
            { word: 'joker' },
            { word: 'interestelar' },
            { word: 'parasite' },
            { word: 'barbie' },
            { word: 'star wars' },
            { word: 'harry potter' },
            { word: 'el padrino' },
            { word: 'jurassic park' },
            { word: 'toy story' },
            { word: 'shrek' },
            { word: 'cars' },
            { word: 'up' },
            { word: 'moana' },
            { word: 'frozen 2' },
            { word: 'rocky' },
            { word: 'creed' },
            { word: 'top gun maverick' },
            { word: 'mission impossible' },
            { word: 'piratas del caribe' },
            { word: 'mi pobre angelito' },
            { word: 'encanto' },
            { word: 'matrix reloaded' },
            { word: 'indiana jones' },
            { word: 'the avengers' },
        ]
    },
    {
        name: 'Musica',
        words: [
            { word: 'rock' },
            { word: 'reggaeton' },
            { word: 'bachata' },
            { word: 'salsa' },
            { word: 'merengue' },
            { word: 'trap' },
            { word: 'indie' },
            { word: 'cumbia' },
            { word: 'reggae' },
            { word: 'metal' },
            { word: 'punk' },
            { word: 'bossa nova' },
            { word: 'jazz' },
            { word: 'blues' },
            { word: 'pop' },
            { word: 'folk' },
            { word: 'clasica' },
            { word: 'opera' },
            { word: 'tango' },
            { word: 'flamenco' },
            { word: 'samba' },
            { word: 'vallenato' },
            { word: 'rap' },
            { word: 'hiphop' },
            { word: 'techno' },
            { word: 'house' },
            { word: 'edm' },
            { word: 'funk' },
            { word: 'soul' },
            { word: 'corridos' },
            { word: 'banda' },
            { word: 'kpop' },
        ]
    },
    {
        name: 'Tecnologia',
        words: [
            { word: 'smartphone' },
            { word: 'laptop' },
            { word: 'drone' },
            { word: 'wifi' },
            { word: 'bluetooth' },
            { word: 'impresora' },
            { word: 'auriculares' },
            { word: 'teclado' },
            { word: 'monitor' },
            { word: 'usb' },
            { word: 'gps' },
            { word: 'robot' },
            { word: 'computador' },
            { word: 'tablet' },
            { word: 'smart tv' },
            { word: 'camara' },
            { word: 'parlante' },
            { word: 'cargador' },
            { word: 'bateria' },
            { word: 'cable' },
            { word: 'microfono' },
            { word: 'consola' },
            { word: 'videojuego' },
            { word: 'navegador' },
            { word: 'app' },
            { word: 'audifonos' },
            { word: 'proyector' },
            { word: 'router' },
            { word: 'modem' },
            { word: 'pantalla' },
            { word: 'smartwatch' },
            { word: 'impresora 3d' },
        ]
    },
    {
        name: 'Ciudades',
        words: [
            { word: 'quito' },
            { word: 'guayaquil' },
            { word: 'cuenca' },
            { word: 'manta' },
            { word: 'bogota' },
            { word: 'lima' },
            { word: 'buenos aires' },
            { word: 'paris' },
            { word: 'londres' },
            { word: 'roma' },
            { word: 'tokio' },
            { word: 'sidney' },
            { word: 'madrid' },
            { word: 'barcelona' },
            { word: 'berlin' },
            { word: 'nueva york' },
            { word: 'miami' },
            { word: 'chicago' },
            { word: 'toronto' },
            { word: 'vancouver' },
            { word: 'mexico' },
            { word: 'cancun' },
            { word: 'rio' },
            { word: 'sao paulo' },
            { word: 'montevideo' },
            { word: 'santiago' },
            { word: 'medellin' },
            { word: 'mendoza' },
            { word: 'rosario' },
            { word: 'bogota' },
            { word: 'guadalajara' },
            { word: 'quito' },
        ]
    },
    {
        name: 'Deportes',
        words: [
            { word: 'futbol' },
            { word: 'basquet' },
            { word: 'voleibol' },
            { word: 'tenis' },
            { word: 'surf' },
            { word: 'boxeo' },
            { word: 'ciclismo' },
            { word: 'karate' },
            { word: 'golf' },
            { word: 'running' },
            { word: 'rugby' },
            { word: 'natacion' },
            { word: 'beisbol' },
            { word: 'hockey' },
            { word: 'cricket' },
            { word: 'badminton' },
            { word: 'pingpong' },
            { word: 'ajedrez' },
            { word: 'esgrima' },
            { word: 'halterofilia' },
            { word: 'patinaje' },
            { word: 'snowboard' },
            { word: 'ski' },
            { word: 'parkour' },
            { word: 'triatlon' },
            { word: 'ironman' },
            { word: 'motocross' },
            { word: 'karting' },
            { word: 'skate' },
            { word: 'bmx' },
            { word: 'taekwondo' },
            { word: 'judo' },
        ]
    },
    {
        name: 'Videojuegos',
        words: [
            { word: 'minecraft' },
            { word: 'fortnite' },
            { word: 'valorant' },
            { word: 'counter strike' },
            { word: 'mario kart' },
            { word: 'zelda' },
            { word: 'pokemon' },
            { word: 'gta' },
            { word: 'fifa' },
            { word: 'league of legends' },
            { word: 'apex' },
            { word: 'overwatch' },
            { word: 'pubg' },
            { word: 'free fire' },
            { word: 'halo' },
            { word: 'gears' },
            { word: 'call of duty' },
            { word: 'fall guys' },
            { word: 'rocket league' },
            { word: 'stardew valley' },
            { word: 'hades' },
            { word: 'among us' },
            { word: 'clash royale' },
            { word: 'clash of clans' },
            { word: 'brawl stars' },
            { word: 'candy crush' },
            { word: 'subway surfers' },
            { word: 'temple run' },
            { word: 'angry birds' },
            { word: 'minecraft dungeons' },
            { word: 'fortnite creative' },
            { word: 'valorant premier' },
        ]
    },
];

export const extraRandomWords = [
    { word: 'leon', hint: 'animal' },
    { word: 'tigre', hint: 'animal' },
    { word: 'oso', hint: 'animal' },
    { word: 'panda', hint: 'animal' },
    { word: 'koala', hint: 'animal' },
    { word: 'delfin', hint: 'animal' },
    { word: 'tortuga', hint: 'animal' },
    { word: 'caballo', hint: 'animal' },
    { word: 'burro', hint: 'animal' },
    { word: 'cordero', hint: 'animal' },
    { word: 'cabra', hint: 'animal' },
    { word: 'pato', hint: 'animal' },
    { word: 'gallina', hint: 'animal' },
    { word: 'gallo', hint: 'animal' },
    { word: 'hipopotamo', hint: 'animal' },
    { word: 'jirafa', hint: 'animal' },
    { word: 'elefante', hint: 'animal' },
    { word: 'hiena', hint: 'animal' },
    { word: 'pantera', hint: 'animal' },
    { word: 'lince', hint: 'animal' },
    { word: 'camello', hint: 'animal' },
    { word: 'ñandu', hint: 'animal' },
    { word: 'lemur', hint: 'animal' },
    { word: 'chimpance', hint: 'animal' },
    { word: 'orangutan', hint: 'animal' },
    { word: 'gorila', hint: 'animal' },
    { word: 'hamster', hint: 'animal' },
    { word: 'conejo', hint: 'animal' },
    { word: 'huron', hint: 'animal' },
    { word: 'erizo', hint: 'animal' },
    { word: 'piraña', hint: 'animal' },
    { word: 'salmon', hint: 'animal' },
    { word: 'trucha', hint: 'animal' },
    { word: 'atun', hint: 'animal' },
    { word: 'pulpo', hint: 'animal' },
    { word: 'calamar', hint: 'animal' },
    { word: 'langosta', hint: 'animal' },
    { word: 'cangrejo', hint: 'animal' },
    { word: 'caracol', hint: 'animal' },
    { word: 'abeja', hint: 'animal' },
    { word: 'avispa', hint: 'animal' },
    { word: 'mariposa', hint: 'animal' },
    { word: 'libelula', hint: 'animal' },
    { word: 'saltamontes', hint: 'animal' },
    { word: 'buho', hint: 'animal' },
    { word: 'zorro', hint: 'animal' },
    { word: 'mapache', hint: 'animal' },
    { word: 'foca', hint: 'animal' },
    { word: 'lobo', hint: 'animal' },
    { word: 'camaleon', hint: 'animal' },
    { word: 'orca', hint: 'animal' },
    { word: 'ballena', hint: 'animal' },
    { word: 'flamenco', hint: 'animal' },
    { word: 'alpaca', hint: 'animal' },
    { word: 'iguana', hint: 'animal' },
    { word: 'perro', hint: 'animal' },
    { word: 'gato', hint: 'animal' },
    { word: 'loro', hint: 'animal' },
    { word: 'canguro', hint: 'animal' },
    { word: 'tiburon', hint: 'animal' },
    { word: 'rinoceronte', hint: 'animal' },
    { word: 'pinguino', hint: 'animal' },
    { word: 'avestruz', hint: 'animal' },
    { word: 'zorrillo', hint: 'animal' },
    { word: 'raton', hint: 'animal' },
    { word: 'topo', hint: 'animal' },
    { word: 'murcielago', hint: 'animal' },
    { word: 'gacela', hint: 'animal' },
    { word: 'buitre', hint: 'animal' },
    { word: 'halcon', hint: 'animal' },
    { word: 'hamburguesa', hint: 'comida' },
    { word: 'tostada', hint: 'comida' },
    { word: 'arequipe', hint: 'comida' },
    { word: 'brownie', hint: 'comida' },
    { word: 'chocolate', hint: 'comida' },
    { word: 'galleta', hint: 'comida' },
    { word: 'panqueque', hint: 'comida' },
    { word: 'waffle', hint: 'comida' },
    { word: 'donut', hint: 'comida' },
    { word: 'croissant', hint: 'comida' },
    { word: 'bagel', hint: 'comida' },
    { word: 'cereal', hint: 'comida' },
    { word: 'granola', hint: 'comida' },
    { word: 'ensalada', hint: 'comida' },
    { word: 'papa', hint: 'comida' },
    { word: 'patacones', hint: 'comida' },
    { word: 'nachos', hint: 'comida' },
    { word: 'guacamole', hint: 'comida' },
    { word: 'burrito', hint: 'comida' },
    { word: 'quesadilla', hint: 'comida' },
    { word: 'empanada', hint: 'comida' },
    { word: 'tamal', hint: 'comida' },
    { word: 'paella', hint: 'comida' },
    { word: 'risotto', hint: 'comida' },
    { word: 'carbonara', hint: 'comida' },
    { word: 'bolognesa', hint: 'comida' },
    { word: 'pesto', hint: 'comida' },
    { word: 'sopa', hint: 'comida' },
    { word: 'curry', hint: 'comida' },
    { word: 'kebab', hint: 'comida' },
    { word: 'falafel', hint: 'comida' },
    { word: 'shawarma', hint: 'comida' },
    { word: 'hummus', hint: 'comida' },
    { word: 'baklava', hint: 'comida' },
    { word: 'cheesecake', hint: 'comida' },
    { word: 'maruchan', hint: 'comida' },
    { word: 'hotdog', hint: 'comida' },
    { word: 'sandwich', hint: 'comida' },
    { word: 'wrap', hint: 'comida' },
    { word: 'yogurt', hint: 'comida' },
    { word: 'smoothie', hint: 'comida' },
    { word: 'milkshake', hint: 'comida' },
    { word: 'arepa', hint: 'comida' },
    { word: 'pizza', hint: 'comida' },
    { word: 'lasagna', hint: 'comida' },
    { word: 'ramen', hint: 'comida' },
    { word: 'sushi', hint: 'comida' },
    { word: 'taco', hint: 'comida' },
    { word: 'gnocchi', hint: 'comida' },
    { word: 'ceviche', hint: 'comida' },
    { word: 'bolon', hint: 'comida' },
    { word: 'encebollado', hint: 'comida' },
    { word: 'torta', hint: 'comida' },
    { word: 'helado', hint: 'comida' },
    { word: 'flan', hint: 'comida' },
    { word: 'tiramisu', hint: 'comida' },
    { word: 'natilla', hint: 'comida' },
    { word: 'churro', hint: 'comida' },
    { word: 'alfajor', hint: 'comida' },
    { word: 'pastel', hint: 'comida' },
    { word: 'tortellini', hint: 'comida' },
    { word: 'ravioli', hint: 'comida' },
    { word: 'focaccia', hint: 'comida' },
    { word: 'bruschetta', hint: 'comida' },
    { word: 'milanesa', hint: 'comida' },
    { word: 'pure', hint: 'comida' },
    { word: 'humita', hint: 'comida' },
    { word: 'locro', hint: 'comida' },
    { word: 'mote', hint: 'comida' },
    { word: 'choclo', hint: 'comida' },
    { word: 'buñuelo', hint: 'comida' },
    { word: 'pandebono', hint: 'comida' },
    { word: 'cachapa', hint: 'comida' },
    { word: 'tequeno', hint: 'comida' },
    { word: 'limonada', hint: 'comida' },
    { word: 'empanadita', hint: 'comida' },
    { word: 'salchipapa', hint: 'comida' },
    { word: 'choripan', hint: 'comida' },
    { word: 'papas', hint: 'comida' },
    { word: 'tacos', hint: 'comida' },
    { word: 'silla', hint: 'objeto' },
    { word: 'mesa', hint: 'objeto' },
    { word: 'puerta', hint: 'objeto' },
    { word: 'ventana', hint: 'objeto' },
    { word: 'lampara', hint: 'objeto' },
    { word: 'sofa', hint: 'objeto' },
    { word: 'cama', hint: 'objeto' },
    { word: 'colchon', hint: 'objeto' },
    { word: 'almohada', hint: 'objeto' },
    { word: 'manta', hint: 'objeto' },
    { word: 'televisor', hint: 'objeto' },
    { word: 'control', hint: 'objeto' },
    { word: 'ventilador', hint: 'objeto' },
    { word: 'calefactor', hint: 'objeto' },
    { word: 'escritorio', hint: 'objeto' },
    { word: 'lapiz', hint: 'objeto' },
    { word: 'boligrafo', hint: 'objeto' },
    { word: 'cuaderno', hint: 'objeto' },
    { word: 'libro', hint: 'objeto' },
    { word: 'estante', hint: 'objeto' },
    { word: 'mochila', hint: 'objeto' },
    { word: 'maleta', hint: 'objeto' },
    { word: 'cartera', hint: 'objeto' },
    { word: 'billetera', hint: 'objeto' },
    { word: 'paraguas', hint: 'objeto' },
    { word: 'gafas', hint: 'objeto' },
    { word: 'reloj', hint: 'objeto' },
    { word: 'espejo', hint: 'objeto' },
    { word: 'cuadro', hint: 'objeto' },
    { word: 'botella', hint: 'objeto' },
    { word: 'vaso', hint: 'objeto' },
    { word: 'plato', hint: 'objeto' },
    { word: 'cuchara', hint: 'objeto' },
    { word: 'tenedor', hint: 'objeto' },
    { word: 'cuchillo', hint: 'objeto' },
    { word: 'sarten', hint: 'objeto' },
    { word: 'olla', hint: 'objeto' },
    { word: 'microondas', hint: 'objeto' },
    { word: 'horno', hint: 'objeto' },
    { word: 'licuadora', hint: 'objeto' },
    { word: 'tostadora', hint: 'objeto' },
    { word: 'cafetera', hint: 'objeto' },
    { word: 'tetera', hint: 'objeto' },
    { word: 'termo', hint: 'objeto' },
    { word: 'celular', hint: 'objeto' },
    { word: 'cargador', hint: 'objeto' },
    { word: 'cable', hint: 'objeto' },
    { word: 'enchufe', hint: 'objeto' },
    { word: 'bateria', hint: 'objeto' },
    { word: 'auricular', hint: 'objeto' },
    { word: 'teclado', hint: 'objeto' },
    { word: 'mouse', hint: 'objeto' },
    { word: 'monitor', hint: 'objeto' },
    { word: 'impresora', hint: 'objeto' },
    { word: 'router', hint: 'objeto' },
    { word: 'modem', hint: 'objeto' },
    { word: 'camara', hint: 'objeto' },
    { word: 'parlante', hint: 'objeto' },
    { word: 'proyector', hint: 'objeto' },
    { word: 'dron', hint: 'objeto' },
    { word: 'linterna', hint: 'objeto' },
    { word: 'encendedor', hint: 'objeto' },
    { word: 'mechero', hint: 'objeto' },
    { word: 'vela', hint: 'objeto' },
    { word: 'foco', hint: 'objeto' },
    { word: 'tornillo', hint: 'objeto' },
    { word: 'martillo', hint: 'objeto' },
    { word: 'clavo', hint: 'objeto' },
    { word: 'destornillador', hint: 'objeto' },
    { word: 'alicate', hint: 'objeto' },
    { word: 'escalera', hint: 'objeto' },
    { word: 'cinta', hint: 'objeto' },
    { word: 'pegamento', hint: 'objeto' },
    { word: 'tijeras', hint: 'objeto' },
    { word: 'regla', hint: 'objeto' },
    { word: 'compas', hint: 'objeto' },
    { word: 'calculadora', hint: 'objeto' },
    { word: 'agenda', hint: 'objeto' },
    { word: 'pincel', hint: 'objeto' },
    { word: 'pintura', hint: 'objeto' },
    { word: 'parque', hint: 'lugar' },
    { word: 'plaza', hint: 'lugar' },
    { word: 'museo', hint: 'lugar' },
    { word: 'teatro', hint: 'lugar' },
    { word: 'cine', hint: 'lugar' },
    { word: 'estadio', hint: 'lugar' },
    { word: 'biblioteca', hint: 'lugar' },
    { word: 'escuela', hint: 'lugar' },
    { word: 'colegio', hint: 'lugar' },
    { word: 'universidad', hint: 'lugar' },
    { word: 'hospital', hint: 'lugar' },
    { word: 'clinica', hint: 'lugar' },
    { word: 'mercado', hint: 'lugar' },
    { word: 'supermercado', hint: 'lugar' },
    { word: 'restaurante', hint: 'lugar' },
    { word: 'cafeteria', hint: 'lugar' },
    { word: 'panaderia', hint: 'lugar' },
    { word: 'banco', hint: 'lugar' },
    { word: 'hotel', hint: 'lugar' },
    { word: 'hostel', hint: 'lugar' },
    { word: 'aeropuerto', hint: 'lugar' },
    { word: 'estacion', hint: 'lugar' },
    { word: 'terminal', hint: 'lugar' },
    { word: 'puerto', hint: 'lugar' },
    { word: 'playa', hint: 'lugar' },
    { word: 'montana', hint: 'lugar' },
    { word: 'bosque', hint: 'lugar' },
    { word: 'desierto', hint: 'lugar' },
    { word: 'lago', hint: 'lugar' },
    { word: 'rio', hint: 'lugar' },
    { word: 'cascada', hint: 'lugar' },
    { word: 'cueva', hint: 'lugar' },
    { word: 'isla', hint: 'lugar' },
    { word: 'valle', hint: 'lugar' },
    { word: 'volcan', hint: 'lugar' },
    { word: 'glaciar', hint: 'lugar' },
    { word: 'pueblo', hint: 'lugar' },
    { word: 'ciudad', hint: 'lugar' },
    { word: 'barrio', hint: 'lugar' },
    { word: 'avenida', hint: 'lugar' },
    { word: 'calle', hint: 'lugar' },
    { word: 'carretera', hint: 'lugar' },
    { word: 'autopista', hint: 'lugar' },
    { word: 'puente', hint: 'lugar' },
    { word: 'tunel', hint: 'lugar' },
    { word: 'malecon', hint: 'lugar' },
    { word: 'mirador', hint: 'lugar' },
    { word: 'costa', hint: 'lugar' },
    { word: 'jardin', hint: 'lugar' },
    { word: 'zoologico', hint: 'lugar' },
    { word: 'acuario', hint: 'lugar' },
    { word: 'feria', hint: 'lugar' },
    { word: 'coliseo', hint: 'lugar' },
    { word: 'templo', hint: 'lugar' },
    { word: 'iglesia', hint: 'lugar' },
    { word: 'catedral', hint: 'lugar' },
    { word: 'mezquita', hint: 'lugar' },
    { word: 'sinagoga', hint: 'lugar' },
    { word: 'monasterio', hint: 'lugar' },
    { word: 'castillo', hint: 'lugar' },
    { word: 'futbol', hint: 'deporte' },
    { word: 'basquet', hint: 'deporte' },
    { word: 'voleibol', hint: 'deporte' },
    { word: 'tenis', hint: 'deporte' },
    { word: 'surf', hint: 'deporte' },
    { word: 'boxeo', hint: 'deporte' },
    { word: 'ciclismo', hint: 'deporte' },
    { word: 'karate', hint: 'deporte' },
    { word: 'golf', hint: 'deporte' },
    { word: 'running', hint: 'deporte' },
    { word: 'rugby', hint: 'deporte' },
    { word: 'natacion', hint: 'deporte' },
    { word: 'beisbol', hint: 'deporte' },
    { word: 'hockey', hint: 'deporte' },
    { word: 'cricket', hint: 'deporte' },
    { word: 'badminton', hint: 'deporte' },
    { word: 'pingpong', hint: 'deporte' },
    { word: 'ajedrez', hint: 'deporte' },
    { word: 'esgrima', hint: 'deporte' },
    { word: 'halterofilia', hint: 'deporte' },
    { word: 'patinaje', hint: 'deporte' },
    { word: 'snowboard', hint: 'deporte' },
    { word: 'ski', hint: 'deporte' },
    { word: 'parkour', hint: 'deporte' },
    { word: 'triatlon', hint: 'deporte' },
    { word: 'ironman', hint: 'deporte' },
    { word: 'motocross', hint: 'deporte' },
    { word: 'formula1', hint: 'deporte' },
    { word: 'karting', hint: 'deporte' },
    { word: 'skate', hint: 'deporte' },
    { word: 'bmx', hint: 'deporte' },
    { word: 'taekwondo', hint: 'deporte' },
    { word: 'judo', hint: 'deporte' },
    { word: 'muaythai', hint: 'deporte' },
    { word: 'mma', hint: 'deporte' },
    { word: 'capoeira', hint: 'deporte' },
    { word: 'gimnasia', hint: 'deporte' },
    { word: 'atletismo', hint: 'deporte' },
    { word: 'billar', hint: 'deporte' },
    { word: 'bowling', hint: 'deporte' },
    { word: 'escalada', hint: 'deporte' },
    { word: 'yoga', hint: 'deporte' },
    { word: 'pilates', hint: 'deporte' },
    { word: 'handball', hint: 'deporte' },
    { word: 'softball', hint: 'deporte' },
    { word: 'rock', hint: 'musica' },
    { word: 'reggaeton', hint: 'musica' },
    { word: 'bachata', hint: 'musica' },
    { word: 'salsa', hint: 'musica' },
    { word: 'merengue', hint: 'musica' },
    { word: 'trap', hint: 'musica' },
    { word: 'indie', hint: 'musica' },
    { word: 'cumbia', hint: 'musica' },
    { word: 'reggae', hint: 'musica' },
    { word: 'metal', hint: 'musica' },
    { word: 'punk', hint: 'musica' },
    { word: 'bossa', hint: 'musica' },
    { word: 'jazz', hint: 'musica' },
    { word: 'blues', hint: 'musica' },
    { word: 'pop', hint: 'musica' },
    { word: 'folk', hint: 'musica' },
    { word: 'clasica', hint: 'musica' },
    { word: 'opera', hint: 'musica' },
    { word: 'tango', hint: 'musica' },
    { word: 'flamenco', hint: 'musica' },
    { word: 'samba', hint: 'musica' },
    { word: 'vallenato', hint: 'musica' },
    { word: 'rap', hint: 'musica' },
    { word: 'hiphop', hint: 'musica' },
    { word: 'country', hint: 'musica' },
    { word: 'techno', hint: 'musica' },
    { word: 'house', hint: 'musica' },
    { word: 'edm', hint: 'musica' },
    { word: 'lofi', hint: 'musica' },
    { word: 'funk', hint: 'musica' },
    { word: 'soul', hint: 'musica' },
    { word: 'corridos', hint: 'musica' },
    { word: 'banda', hint: 'musica' },
    { word: 'kpop', hint: 'musica' },
    { word: 'balada', hint: 'musica' },
    { word: 'camiseta', hint: 'ropa' },
    { word: 'zapatillas', hint: 'ropa' },
    { word: 'jeans', hint: 'ropa' },
    { word: 'chaqueta', hint: 'ropa' },
    { word: 'gorra', hint: 'ropa' },
    { word: 'bufanda', hint: 'ropa' },
    { word: 'guantes', hint: 'ropa' },
    { word: 'calcetines', hint: 'ropa' },
    { word: 'vestido', hint: 'ropa' },
    { word: 'falda', hint: 'ropa' },
    { word: 'traje', hint: 'ropa' },
    { word: 'blazer', hint: 'ropa' },
    { word: 'corbata', hint: 'ropa' },
    { word: 'sueter', hint: 'ropa' },
    { word: 'sudadera', hint: 'ropa' },
    { word: 'pantalon', hint: 'ropa' },
    { word: 'bermuda', hint: 'ropa' },
    { word: 'short', hint: 'ropa' },
    { word: 'botas', hint: 'ropa' },
    { word: 'sandalias', hint: 'ropa' },
    { word: 'sombrero', hint: 'ropa' },
    { word: 'boina', hint: 'ropa' },
    { word: 'poncho', hint: 'ropa' },
    { word: 'gabardina', hint: 'ropa' },
    { word: 'pijama', hint: 'ropa' },
    { word: 'bata', hint: 'ropa' },
    { word: 'chaleco', hint: 'ropa' },
    { word: 'medias', hint: 'ropa' },
    { word: 'cinturon', hint: 'ropa' },
    { word: 'tenis', hint: 'ropa' },
    { word: 'pantaloneta', hint: 'ropa' },
    { word: 'overall', hint: 'ropa' },
    { word: 'gorro', hint: 'ropa' },
    { word: 'lluvia', hint: 'clima' },
    { word: 'viento', hint: 'clima' },
    { word: 'trueno', hint: 'clima' },
    { word: 'relampago', hint: 'clima' },
    { word: 'nube', hint: 'clima' },
    { word: 'sol', hint: 'clima' },
    { word: 'luna', hint: 'clima' },
    { word: 'estrella', hint: 'clima' },
    { word: 'cielo', hint: 'clima' },
    { word: 'huracan', hint: 'clima' },
    { word: 'tornado', hint: 'clima' },
    { word: 'neblina', hint: 'clima' },
    { word: 'granizo', hint: 'clima' },
    { word: 'nieve', hint: 'clima' },
    { word: 'ola', hint: 'clima' },
    { word: 'marea', hint: 'clima' },
    { word: 'brisa', hint: 'clima' },
    { word: 'otono', hint: 'clima' },
    { word: 'invierno', hint: 'clima' },
    { word: 'verano', hint: 'clima' },
    { word: 'primavera', hint: 'clima' },
    { word: 'seismo', hint: 'clima' },
    { word: 'temblor', hint: 'clima' },
    { word: 'terremoto', hint: 'clima' },
    { word: 'arcoiris', hint: 'clima' },
    { word: 'avion', hint: 'transporte' },
    { word: 'tren', hint: 'transporte' },
    { word: 'metro', hint: 'transporte' },
    { word: 'taxi', hint: 'transporte' },
    { word: 'uber', hint: 'transporte' },
    { word: 'bicicleta', hint: 'transporte' },
    { word: 'patineta', hint: 'transporte' },
    { word: 'scooter', hint: 'transporte' },
    { word: 'moto', hint: 'transporte' },
    { word: 'auto', hint: 'transporte' },
    { word: 'camioneta', hint: 'transporte' },
    { word: 'tractor', hint: 'transporte' },
    { word: 'barco', hint: 'transporte' },
    { word: 'yate', hint: 'transporte' },
    { word: 'velero', hint: 'transporte' },
    { word: 'crucero', hint: 'transporte' },
    { word: 'ferry', hint: 'transporte' },
    { word: 'globo', hint: 'transporte' },
    { word: 'helicoptero', hint: 'transporte' },
    { word: 'tranvia', hint: 'transporte' },
    { word: 'bus', hint: 'transporte' },
    { word: 'camion', hint: 'transporte' },
    { word: 'patinete', hint: 'transporte' },
    { word: 'monopatin', hint: 'transporte' },
    { word: 'trineo', hint: 'transporte' },
    { word: 'cuatrimoto', hint: 'transporte' },
    { word: 'segway', hint: 'transporte' },
    { word: 'cohete', hint: 'transporte' },
    { word: 'bote', hint: 'transporte' },
    { word: 'kayak', hint: 'transporte' },
    { word: 'rojo', hint: 'color' },
    { word: 'azul', hint: 'color' },
    { word: 'verde', hint: 'color' },
    { word: 'amarillo', hint: 'color' },
    { word: 'negro', hint: 'color' },
    { word: 'blanco', hint: 'color' },
    { word: 'gris', hint: 'color' },
    { word: 'rosa', hint: 'color' },
    { word: 'morado', hint: 'color' },
    { word: 'naranja', hint: 'color' },
    { word: 'beige', hint: 'color' },
    { word: 'marron', hint: 'color' },
    { word: 'cian', hint: 'color' },
    { word: 'magenta', hint: 'color' },
    { word: 'dorado', hint: 'color' },
    { word: 'plateado', hint: 'color' },
    { word: 'turquesa', hint: 'color' },
    { word: 'crema', hint: 'color' },
    { word: 'violeta', hint: 'color' },
    { word: 'celeste', hint: 'color' },
    { word: 'doctor', hint: 'oficio' },
    { word: 'enfermero', hint: 'oficio' },
    { word: 'maestro', hint: 'oficio' },
    { word: 'ingeniero', hint: 'oficio' },
    { word: 'abogado', hint: 'oficio' },
    { word: 'arquitecto', hint: 'oficio' },
    { word: 'disenador', hint: 'oficio' },
    { word: 'artista', hint: 'oficio' },
    { word: 'fotografo', hint: 'oficio' },
    { word: 'chef', hint: 'oficio' },
    { word: 'panadero', hint: 'oficio' },
    { word: 'barista', hint: 'oficio' },
    { word: 'mecanico', hint: 'oficio' },
    { word: 'carpintero', hint: 'oficio' },
    { word: 'plomero', hint: 'oficio' },
    { word: 'electricista', hint: 'oficio' },
    { word: 'agricultor', hint: 'oficio' },
    { word: 'piloto', hint: 'oficio' },
    { word: 'azafata', hint: 'oficio' },
    { word: 'conductor', hint: 'oficio' },
    { word: 'bombero', hint: 'oficio' },
    { word: 'policia', hint: 'oficio' },
];
